public let clientId = "00f34fed06ffad73fe17"
public let serverHostname = "canopy.codebasesaga.com"
public let serverBaseUri = "https://\(serverHostname)"
public let redirectUri = "\(serverBaseUri)/oauth"
public let hookUri = "\(serverBaseUri)/github"
